services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'  # Changed host port to 3307 to avoid conflict
    environment:
      MYSQL_DATABASE: 'django_todo_list'
      MYSQL_ROOT_PASSWORD: 'password'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todo_list
    ports:
      - "8000:8000"
    depends_on:
      - db

