# Generated by Django 2.2.2 on 2019-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='list_id',
            field=models.IntegerField(default=-1),
        ),
    ]
